# Generated by Django 3.2.16 on 2022-12-31 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0006_auto_20221231_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='like',
        ),
    ]
