# Generated by Django 3.2.16 on 2022-12-22 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribeapp', '0002_auto_20221222_1654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-pk']},
        ),
    ]
