# Generated by Django 3.2.16 on 2023-01-01 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0006_project_writer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='writer',
        ),
    ]
