# Generated by Django 4.1.4 on 2023-01-12 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('summary', '0013_remove_tbsentimental_news_keyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbTradingInfo',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, db_column='date', null=True)),
                ('val_institution', models.IntegerField(blank=True, db_column='institution', null=True)),
                ('val_retail_investor', models.IntegerField(blank=True, db_column='val_retail_investor', null=True)),
                ('val_etc_corporation', models.IntegerField(blank=True, db_column='val_etc_corporation', null=True)),
                ('val_foreigner', models.IntegerField(blank=True, db_column='val_foreigner', null=True)),
                ('vol_institution', models.IntegerField(blank=True, db_column='vol_institution', null=True)),
                ('vol_retail_investor', models.IntegerField(blank=True, db_column='vol_retail_investor', null=True)),
                ('vol_etc_corporation', models.IntegerField(blank=True, db_column='vol_etc_corporation', null=True)),
                ('vol_foreigner', models.IntegerField(blank=True, db_column='vol_foreigner', null=True)),
                ('holding_volume', models.IntegerField(blank=True, db_column='holding_volume', null=True)),
                ('shareholding', models.IntegerField(blank=True, db_column='shareholding', null=True)),
                ('limit_volume', models.IntegerField(blank=True, db_column='limit_volume', null=True)),
                ('exhaustion_rate', models.IntegerField(blank=True, db_column='exhaustion_rate', null=True)),
                ('short_balance', models.IntegerField(blank=True, db_column='balance', null=True)),
                ('short_value', models.IntegerField(blank=True, db_column='value', null=True)),
                ('short_weight', models.IntegerField(blank=True, db_column='weight', null=True)),
                ('market_cap', models.IntegerField(blank=True, db_column='market_cap', null=True)),
                ('updated_date', models.DateTimeField(blank=True, db_column='updated_date', null=True)),
                ('code', models.ForeignKey(db_column='code', on_delete=django.db.models.deletion.DO_NOTHING, to='summary.tbname')),
            ],
            options={
                'db_table': 'tb_tradinfo',
            },
        ),
        migrations.CreateModel(
            name='TbProfit',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('date', models.IntegerField(blank=True, db_column='date', null=True)),
                ('profit', models.IntegerField(blank=True, db_column='profit', null=True)),
                ('updated_date', models.DateTimeField(blank=True, db_column='updated_date', null=True)),
                ('code', models.ForeignKey(db_column='code', on_delete=django.db.models.deletion.DO_NOTHING, to='summary.tbname')),
            ],
            options={
                'db_table': 'tb_profit',
            },
        ),
        migrations.CreateModel(
            name='TbOHLCV',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, db_column='date', null=True)),
                ('compare_price', models.FloatField(blank=True, db_column='compare_price', null=True)),
                ('open_price', models.IntegerField(blank=True, db_column='open_price', null=True)),
                ('high_price', models.IntegerField(blank=True, db_column='high_price', null=True)),
                ('low_price', models.IntegerField(blank=True, db_column='low_price', null=True)),
                ('close_price', models.IntegerField(blank=True, db_column='close_price', null=True)),
                ('trading_volume', models.IntegerField(blank=True, db_column='trading_volume', null=True)),
                ('trading_value', models.IntegerField(blank=True, db_column='trading_value', null=True)),
                ('news_keyword', models.TextField(blank=True, db_column='news_keyword', null=True)),
                ('BPS', models.FloatField(blank=True, db_column='BPS', null=True)),
                ('PER', models.FloatField(blank=True, db_column='PER', null=True)),
                ('PBR', models.FloatField(blank=True, db_column='PBR', null=True)),
                ('EPS', models.FloatField(blank=True, db_column='EPS', null=True)),
                ('DIV', models.FloatField(blank=True, db_column='DIV', null=True)),
                ('DPS', models.FloatField(blank=True, db_column='DPS', null=True)),
                ('updated_date', models.DateTimeField(blank=True, db_column='updated_date', null=True)),
                ('code', models.ForeignKey(db_column='code', on_delete=django.db.models.deletion.DO_NOTHING, to='summary.tbname')),
            ],
            options={
                'db_table': 'tb_ohlcv',
            },
        ),
    ]
