# Generated by Django 4.1.4 on 2022-12-30 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("summary", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TbTradingVolume",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                ("date", models.DateTimeField(blank=True, db_column="date", null=True)),
                (
                    "institution",
                    models.IntegerField(blank=True, db_column="institution", null=True),
                ),
                (
                    "retail_investor",
                    models.IntegerField(
                        blank=True, db_column="retail_investor", null=True
                    ),
                ),
                (
                    "etc_corporation",
                    models.IntegerField(
                        blank=True, db_column="etc_corporation", null=True
                    ),
                ),
                (
                    "foreigner",
                    models.IntegerField(blank=True, db_column="foreigner", null=True),
                ),
                (
                    "code",
                    models.ForeignKey(
                        db_column="code",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="summary.tbname",
                    ),
                ),
            ],
            options={"db_table": "tb_tdvolume",},
        ),
        migrations.CreateModel(
            name="TbTradingValue",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                ("date", models.DateTimeField(blank=True, db_column="date", null=True)),
                (
                    "institution",
                    models.IntegerField(blank=True, db_column="institution", null=True),
                ),
                (
                    "retail_investor",
                    models.IntegerField(
                        blank=True, db_column="retail_investor", null=True
                    ),
                ),
                (
                    "etc_corporation",
                    models.IntegerField(
                        blank=True, db_column="etc_corporation", null=True
                    ),
                ),
                (
                    "foreigner",
                    models.IntegerField(blank=True, db_column="foreigner", null=True),
                ),
                (
                    "code",
                    models.ForeignKey(
                        db_column="code",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="summary.tbname",
                    ),
                ),
            ],
            options={"db_table": "tb_tdvalue",},
        ),
        migrations.CreateModel(
            name="TbShort",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                ("date", models.DateTimeField(blank=True, db_column="date", null=True)),
                (
                    "balance",
                    models.IntegerField(blank=True, db_column="balance", null=True),
                ),
                (
                    "volume",
                    models.IntegerField(blank=True, db_column="volume", null=True),
                ),
                (
                    "value",
                    models.IntegerField(blank=True, db_column="value", null=True),
                ),
                (
                    "market_cap",
                    models.IntegerField(blank=True, db_column="market_cap", null=True),
                ),
                (
                    "weight",
                    models.IntegerField(blank=True, db_column="weight", null=True),
                ),
                (
                    "code",
                    models.ForeignKey(
                        db_column="code",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="summary.tbname",
                    ),
                ),
            ],
            options={"db_table": "tb_short",},
        ),
        migrations.CreateModel(
            name="TbProfit",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                ("date", models.DateTimeField(blank=True, db_column="date", null=True)),
                (
                    "profit",
                    models.IntegerField(blank=True, db_column="profit", null=True),
                ),
                (
                    "code",
                    models.ForeignKey(
                        db_column="code",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="summary.tbname",
                    ),
                ),
            ],
            options={"db_table": "tb_profit",},
        ),
        migrations.CreateModel(
            name="TbOHLCV",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                ("date", models.DateTimeField(blank=True, db_column="date", null=True)),
                (
                    "compare_price",
                    models.FloatField(blank=True, db_column="compare_price", null=True),
                ),
                (
                    "open_price",
                    models.IntegerField(blank=True, db_column="open_price", null=True),
                ),
                (
                    "high_price",
                    models.IntegerField(blank=True, db_column="high_price", null=True),
                ),
                (
                    "low_price",
                    models.IntegerField(blank=True, db_column="low_price", null=True),
                ),
                (
                    "close_price",
                    models.IntegerField(blank=True, db_column="close_price", null=True),
                ),
                (
                    "trading_volume",
                    models.IntegerField(
                        blank=True, db_column="trading_volume", null=True
                    ),
                ),
                (
                    "trading_value",
                    models.IntegerField(
                        blank=True, db_column="trading_value", null=True
                    ),
                ),
                (
                    "code",
                    models.ForeignKey(
                        db_column="code",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="summary.tbname",
                    ),
                ),
            ],
            options={"db_table": "tb_ohlcv",},
        ),
        migrations.CreateModel(
            name="TbFundamental",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                ("date", models.DateTimeField(blank=True, db_column="date", null=True)),
                ("BPS", models.FloatField(blank=True, db_column="BPS", null=True)),
                ("PER", models.FloatField(blank=True, db_column="PER", null=True)),
                ("PBR", models.FloatField(blank=True, db_column="PBR", null=True)),
                ("EPS", models.FloatField(blank=True, db_column="EPS", null=True)),
                ("DIV", models.FloatField(blank=True, db_column="DIV", null=True)),
                ("DPS", models.FloatField(blank=True, db_column="DPS", null=True)),
                (
                    "code",
                    models.ForeignKey(
                        db_column="code",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="summary.tbname",
                    ),
                ),
            ],
            options={"db_table": "tb_fundmental",},
        ),
        migrations.CreateModel(
            name="TbForeignerInvestment",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "volume",
                    models.IntegerField(blank=True, db_column="volume", null=True),
                ),
                (
                    "holding_volume",
                    models.IntegerField(
                        blank=True, db_column="holding_volume", null=True
                    ),
                ),
                (
                    "shareholding",
                    models.IntegerField(
                        blank=True, db_column="shareholding", null=True
                    ),
                ),
                (
                    "limit_volume",
                    models.IntegerField(
                        blank=True, db_column="limit_volume", null=True
                    ),
                ),
                (
                    "exhaustion_rate",
                    models.IntegerField(
                        blank=True, db_column="exhaustion_rate", null=True
                    ),
                ),
                (
                    "code",
                    models.ForeignKey(
                        db_column="code",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="summary.tbname",
                    ),
                ),
            ],
            options={"db_table": "tb_forinv",},
        ),
    ]
