# Generated by Django 4.1.4 on 2022-12-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tbforeignerinvestment",
            name="date",
            field=models.DateTimeField(blank=True, db_column="date", null=True),
        ),
    ]
