# Generated by Django 4.1.4 on 2023-01-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbohlcv',
            name='news_keyword',
            field=models.JSONField(db_column='news_keyword', default=dict),
        ),
    ]
