# Generated by Django 4.1.4 on 2023-01-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_tbohlcv_news_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbohlcv',
            name='news_keyword',
            field=models.TextField(db_column='news_keyword', default=dict),
        ),
    ]
