# Generated by Django 3.2.16 on 2023-01-04 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_tbohlcv_trading_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbprofit',
            name='date',
            field=models.IntegerField(blank=True, db_column='date', null=True),
        ),
    ]
