# Generated by Django 4.1.4 on 2023-01-13 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_tbohlcv_news_keyword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbohlcv',
            name='DIV',
        ),
        migrations.AddField(
            model_name='tbohlcv',
            name='DIVy',
            field=models.FloatField(blank=True, db_column='DIVy', null=True),
        ),
    ]
