# Generated by Django 4.1.4 on 2023-01-13 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_remove_tbohlcv_div_tbohlcv_divy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbohlcv',
            name='trading_value',
            field=models.BigIntegerField(blank=True, db_column='trading_value', null=True),
        ),
    ]
