# Generated by Django 4.1.4 on 2023-01-13 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_tbohlcv_trading_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbohlcv',
            name='news_keyword',
            field=models.TextField(db_column='news_keyword', default=dict, null=True),
        ),
    ]
