# Generated by Django 4.1.4 on 2023-01-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0006_alter_tbohlcv_news_keyword"),
    ]

    operations = [
        migrations.RemoveField(model_name="tbohlcv", name="updated_date",),
        migrations.AddField(
            model_name="tbohlcv",
            name="count",
            field=models.CharField(
                blank=True, db_column="count", max_length=64, null=True
            ),
        ),
        migrations.AddField(
            model_name="tbohlcv",
            name="predict",
            field=models.CharField(
                blank=True, db_column="predict", max_length=16, null=True
            ),
        ),
    ]
