# Generated by Django 4.1.4 on 2023-01-18 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0007_remove_tbohlcv_updated_date_tbohlcv_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="tbtradinginfo", name="market_cap",),
    ]
