# Generated by Django 4.1.4 on 2023-01-19 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0008_remove_tbtradinginfo_market_cap"),
    ]

    operations = [
        migrations.AddField(
            model_name="tbohlcv",
            name="updated_date",
            field=models.DateTimeField(blank=True, db_column="updated_date", null=True),
        ),
        migrations.AlterField(
            model_name="tbtradinginfo",
            name="short_balance",
            field=models.IntegerField(blank=True, db_column="short_balance", null=True),
        ),
        migrations.AlterField(
            model_name="tbtradinginfo",
            name="short_value",
            field=models.IntegerField(blank=True, db_column="short_value", null=True),
        ),
        migrations.AlterField(
            model_name="tbtradinginfo",
            name="short_weight",
            field=models.IntegerField(blank=True, db_column="short_weight", null=True),
        ),
        migrations.AlterField(
            model_name="tbtradinginfo",
            name="val_institution",
            field=models.IntegerField(
                blank=True, db_column="val_institution", null=True
            ),
        ),
    ]
