# Generated by Django 3.2.16 on 2022-12-31 02:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectapp', '0005_auto_20221231_1130'),
        ('subscribeapp', '0004_alter_subscription_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('user', 'project')},
        ),
    ]
