# Generated by Django 3.2.16 on 2022-12-19 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commentapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_ay',
            new_name='created_at',
        ),
    ]
