# Generated by Django 4.1.5 on 2023-01-04 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("summary", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="tbreport", name="content",),
        migrations.RemoveField(model_name="tbreport", name="title",),
        migrations.RemoveField(model_name="tbsentimental", name="report",),
        migrations.AddField(
            model_name="tbname",
            name="market",
            field=models.IntegerField(db_column="market", null=True),
        ),
    ]
