# Generated by Django 4.1.4 on 2023-01-10 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("summary", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tbsentimental",
            name="date",
            field=models.DateTimeField(blank=True, db_column="date", null=True),
        ),
    ]
