# Generated by Django 4.1.4 on 2023-01-10 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("summary", "0002_tbsentimental_date"),
    ]

    operations = [
        migrations.RemoveField(model_name="tbname", name="volume",),
        migrations.AddField(
            model_name="tbname",
            name="market_cap",
            field=models.IntegerField(blank=True, db_column="market_cap", null=True),
        ),
    ]
