# Generated by Django 4.1.5 on 2023-01-04 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("summary", "0002_remove_tbreport_content_remove_tbreport_title_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="tbinfo", name="settlement_date",),
    ]
