# Generated by Django 3.2.16 on 2023-01-04 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0003_remove_tbinfo_settlement_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbinfo',
            name='established_date',
        ),
        migrations.RemoveField(
            model_name='tbinfo',
            name='tel',
        ),
        migrations.AddField(
            model_name='tbinfo',
            name='homepage',
            field=models.CharField(blank=True, db_column='homepage', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='tbinfo',
            name='sector',
            field=models.CharField(blank=True, db_column='sector', max_length=32, null=True),
        ),
    ]
