# Generated by Django 4.1.4 on 2023-01-10 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("summary", "0003_remove_tbname_volume_tbname_market_cap"),
    ]

    operations = [
        migrations.RemoveField(model_name="tbname", name="market_cap",),
        migrations.AddField(
            model_name="tbname",
            name="volume",
            field=models.IntegerField(blank=True, db_column="volume", null=True),
        ),
    ]
