# Generated by Django 4.1.4 on 2023-01-10 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("summary", "0004_remove_tbname_market_cap_tbname_volume"),
    ]

    operations = [
        migrations.RemoveField(model_name="tbname", name="volume",),
        migrations.AddField(
            model_name="tbname",
            name="market_cap",
            field=models.IntegerField(blank=True, db_column="market_cap", null=True),
        ),
    ]
