# Generated by Django 3.2.16 on 2023-01-05 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0004_auto_20230105_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbinfo',
            name='CEO',
            field=models.CharField(blank=True, db_column='CEO', max_length=64, null=True),
        ),
    ]
