# Generated by Django 4.1.4 on 2023-01-10 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("summary", "0005_remove_tbname_volume_tbname_market_cap"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tbname",
            name="market_cap",
            field=models.BigIntegerField(blank=True, db_column="market_cap", null=True),
        ),
    ]
