# Generated by Django 3.2.16 on 2023-01-05 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0005_alter_tbinfo_ceo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbinfo',
            name='sector',
            field=models.CharField(blank=True, db_column='sector', max_length=64, null=True),
        ),
    ]
