# Generated by Django 4.1.4 on 2023-01-10 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("summary", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tbname",
            name="sector",
            field=models.CharField(
                blank=True, db_column="sector", max_length=64, null=True
            ),
        ),
    ]
