# Generated by Django 4.1.4 on 2023-01-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0007_alter_tbname_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbreport',
            name='comment',
            field=models.CharField(blank=True, db_column='comment', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='tbreport',
            name='price',
            field=models.CharField(blank=True, db_column='price', max_length=8, null=True),
        ),
    ]
