# Generated by Django 4.1.4 on 2023-01-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0008_alter_tbreport_comment_alter_tbreport_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbsentimental',
            name='news_keyword',
            field=models.TextField(blank=True, db_column='news_keyword', null=True),
        ),
    ]
