# Generated by Django 4.1.4 on 2023-01-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0009_tbsentimental_news_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbreport',
            name='price',
            field=models.CharField(blank=True, db_column='price', max_length=16, null=True),
        ),
    ]
