# Generated by Django 4.1.4 on 2023-01-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0010_alter_tbreport_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbsentimental',
            name='comment',
            field=models.TextField(blank=True, db_column='comment', null=True),
        ),
    ]
