# Generated by Django 4.1.4 on 2023-01-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0011_alter_tbsentimental_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbsentimental',
            name='news_graph',
            field=models.TextField(blank=True, db_column='news_graph', null=True),
        ),
    ]
