# Generated by Django 4.1.4 on 2023-01-12 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0012_tbsentimental_news_graph'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbsentimental',
            name='news_keyword',
        ),
    ]
