# Generated by Django 4.1.4 on 2023-01-09 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("summary", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TbNews",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                ("date", models.DateTimeField(blank=True, db_column="date", null=True)),
                (
                    "press",
                    models.CharField(
                        blank=True, db_column="press", max_length=16, null=True
                    ),
                ),
                ("url", models.TextField(blank=True, db_column="url", null=True)),
                (
                    "title",
                    models.CharField(
                        blank=True, db_column="title", max_length=64, null=True
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, db_column="content", null=True),
                ),
                (
                    "photourl",
                    models.CharField(
                        blank=True, db_column="photourl", max_length=255, null=True
                    ),
                ),
                ("graph", models.TextField(blank=True, db_column="graph", null=True)),
                (
                    "updated_date",
                    models.DateTimeField(
                        blank=True, db_column="updated_date", null=True
                    ),
                ),
                (
                    "code",
                    models.ForeignKey(
                        db_column="code",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="summary.tbname",
                    ),
                ),
            ],
            options={"db_table": "tb_news",},
        ),
    ]
