# Generated by Django 4.1.4 on 2023-01-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tbnews",
            name="photourl",
            field=models.TextField(blank=True, db_column="photourl", null=True),
        ),
    ]
