# Generated by Django 3.2.16 on 2023-01-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_tbnews_date_cate_remove_tbnews_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbnews',
            name='title',
            field=models.CharField(blank=True, db_column='title', max_length=64, null=True),
        ),
    ]
