# Generated by Django 3.2.16 on 2023-01-10 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_tbnews_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbnews',
            name='graph',
        ),
    ]
