# Generated by Django 4.1.4 on 2023-01-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_tbnews_graph'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbnews',
            name='graph',
            field=models.TextField(blank=True, db_column='graph', null=True),
        ),
    ]
