# Generated by Django 3.2.16 on 2023-01-11 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_tbnews_graph'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbnews',
            name='graph',
        ),
    ]
